-- MySQL Script generated by MySQL Workbench
-- 09/07/16 21:39:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema consejeros
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `consejeros` ;

-- -----------------------------------------------------
-- Schema consejeros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consejeros` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `consejeros` ;

-- -----------------------------------------------------
-- Table `consejeros`.`consejero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consejeros`.`consejero` ;

CREATE TABLE IF NOT EXISTS `consejeros`.`consejero` (
  `idconsejero` INT NOT NULL COMMENT '',
  `nombre_consejero` VARCHAR(45) NOT NULL COMMENT '',
  `apellido_paterno_consejero` VARCHAR(45) NOT NULL COMMENT '',
  `apellido_materno_consejero` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idconsejero`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consejeros`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consejeros`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `consejeros`.`estudiante` (
  `boleta` VARCHAR(10) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido_paterno` VARCHAR(45) NOT NULL COMMENT '',
  `apellido_materno` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` VARCHAR(20) NOT NULL COMMENT '',
  `fecha_nac` DATE NOT NULL COMMENT '',
  `consejero_idconsejero` INT NOT NULL COMMENT '',
  PRIMARY KEY (`boleta`, `consejero_idconsejero`)  COMMENT '',
  INDEX `fk_estudiante_consejero_idx` (`consejero_idconsejero` ASC)  COMMENT '',
  CONSTRAINT `fk_estudiante_consejero`
    FOREIGN KEY (`consejero_idconsejero`)
    REFERENCES `consejeros`.`consejero` (`idconsejero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consejeros`.`tipo_personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consejeros`.`tipo_personal` ;

CREATE TABLE IF NOT EXISTS `consejeros`.`tipo_personal` (
  `idtipo_personal` INT NOT NULL COMMENT '',
  `nombre_puesto` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtipo_personal`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consejeros`.`moderador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consejeros`.`moderador` ;

CREATE TABLE IF NOT EXISTS `consejeros`.`moderador` (
  `idmoderador` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `tipo_personal_idtipo_personal` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idmoderador`, `tipo_personal_idtipo_personal`)  COMMENT '',
  INDEX `fk_moderador_tipo_personal1_idx` (`tipo_personal_idtipo_personal` ASC)  COMMENT '',
  CONSTRAINT `fk_moderador_tipo_personal1`
    FOREIGN KEY (`tipo_personal_idtipo_personal`)
    REFERENCES `consejeros`.`tipo_personal` (`idtipo_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consejeros`.`club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consejeros`.`club` ;

CREATE TABLE IF NOT EXISTS `consejeros`.`club` (
  `idclub` INT NOT NULL COMMENT '',
  `nombre_club` VARCHAR(45) NULL COMMENT '',
  `moderador_idmoderador` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idclub`, `moderador_idmoderador`)  COMMENT '',
  INDEX `fk_club_moderador1_idx` (`moderador_idmoderador` ASC)  COMMENT '',
  CONSTRAINT `fk_club_moderador1`
    FOREIGN KEY (`moderador_idmoderador`)
    REFERENCES `consejeros`.`moderador` (`idmoderador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consejeros`.`estudiante_club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consejeros`.`estudiante_club` ;

CREATE TABLE IF NOT EXISTS `consejeros`.`estudiante_club` (
  `club_idclub` INT NOT NULL COMMENT '',
  `estudiante_boleta` VARCHAR(10) NOT NULL COMMENT '',
  `estudiante_club_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`club_idclub`, `estudiante_boleta`, `estudiante_club_id`)  COMMENT '',
  INDEX `fk_estudiante_club_club1_idx` (`club_idclub` ASC)  COMMENT '',
  INDEX `fk_estudiante_club_estudiante1_idx` (`estudiante_boleta` ASC, `estudiante_club_id` ASC)  COMMENT '',
  CONSTRAINT `fk_estudiante_club_club1`
    FOREIGN KEY (`club_idclub`)
    REFERENCES `consejeros`.`club` (`idclub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_club_estudiante1`
    FOREIGN KEY (`estudiante_boleta` , `estudiante_club_id`)
    REFERENCES `consejeros`.`estudiante` (`boleta` , `consejero_idconsejero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consejeros`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consejeros`.`actividad` ;

CREATE TABLE IF NOT EXISTS `consejeros`.`actividad` (
  `idactividad` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `club_idclub` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idactividad`, `club_idclub`)  COMMENT '',
  INDEX `fk_actividad_club1_idx` (`club_idclub` ASC)  COMMENT '',
  CONSTRAINT `fk_actividad_club1`
    FOREIGN KEY (`club_idclub`)
    REFERENCES `consejeros`.`club` (`idclub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
